### ISSUE TITLE
Class method naming

### ISSUE THREAD

**Issue by rosle** [munirehmad/agoogle_search_tool#13]
Small comment for the class method naming. 

```ruby
  def self.GetForKW kw
  def self.GetSortedByKW
```

Would it be good if we follow ruby convention that we should use lower snake case for method name.

**Comment by munirehmad** [comment]
Sorry, writing Go for last year and being OOL for Ruby...

**Comment by munirehmad** [comment]
Fixed by https://github.com/munirehmad/agoogle_search_tool/pull/15
