### ISSUE TITLE
Anonymous user can access users page

### ISSUE THREAD

**Issue by rosle** [munirehmad/agoogle_search_tool#8]
Currently we can visit the users page (http://localhost:3000/users) without logging in. This might not be good as anyone can go to the url and see everyone username and password. I think we might need to the authentication on that page. And for a new user, we can make a simple register page for them.

Another option is to manually seed users to the database as currently you didn't use any gem for authentication.

**Comment by rosle** [comment]
Another comment is for the password field, I think we better use the input type password for it 👍

**Comment by munirehmad** [comment]
I've removed the scaffolding. Added a default user to Seeds.

Added register option on homepage.

**Comment by munirehmad** [comment]
fixed by #17
